# Generated by Django 5.2.4 on 2025-08-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='online_participants',
            field=models.IntegerField(default=0),
        ),
    ]
